name: Build Skyrim AE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PRESET: "vs2022-windows-vcpkg-ae"
  VCPKG_ROOT: ${{ github.workspace }}\vcpkg
      
jobs:
  build:
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4

    - name: 🔽 Update VCPKG
      run: |
          git clone https://github.com/microsoft/vcpkg ${{ env.VCPKG_ROOT }}
          cd "${{ env.VCPKG_ROOT }}"
          bootstrap-vcpkg.bat -disableMetric
    - name: Configure CMake
      run: cmake --preset ${{env.PRESET}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build --preset ${{env.PRESET}}

