name: Build Skyrim AE

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  PRESET: "vs2022-windows-vcpkg-se"
  VCPKG_ROOT: ${{ github.workspace }}\vcpkg
  PROJECT_NAME: LightingUtil-SE
      
jobs:
  build:
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v4

    - name: 🔽 Update VCPKG
      run: |
          git clone https://github.com/microsoft/vcpkg ${{ env.VCPKG_ROOT }}
          cd "${{ env.VCPKG_ROOT }}"
          bootstrap-vcpkg.bat -disableMetric
    - name: Configure CMake
      run: cmake --preset ${{env.PRESET}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build --preset ${{env.PRESET}}
    - name: Archive
      run: 7z a $PROJECT_NAME.zip ./buildae/release/*.*
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: |
            ${{ env.PROJECT_NAME }}.zip
    - name: Create & Upload Release
      id: upload-release
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.PROJECT_NAME }}.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        name: ${{ env.PROJECT_NAME }} ${{ github.ref_name }}